```{r}
ggplot(data = tabela_observado_estimado) +
  geom_point(aes(x = v1, y = v2), color = "blue", fill = "white") +
  geom_abline(col = "yellow") +
  geom_abline(
    aes(slope = coeficientes[2], intercept = coeficientes[1]),
    col = "red"
  ) +
  labs(x = "Observado", y = "Estimado") +
  scale_y_continuous(
    labels = scales::number_format(big.mark = ".", accuracy = 1)
  ) +
  scale_x_continuous(
    labels = scales::number_format(big.mark = ".", accuracy = 1)
  ) +
  theme_bw()
```

```{r}
  ggplot(tabela_estimado_residuo) +
    geom_point(
      aes(x = est, y = res, fill = out),
      col = "blue4",
      stroke = 0.84,
      shape = 21,
      show.legend = F
    ) +
    geom_abline(aes(intercept = 0, slope = 0), col = "blue") +
    geom_abline(aes(intercept = 2, slope = 0), col = "red") +
    geom_abline(aes(intercept = -2, slope = 0), col = "red") +
    labs(y = "Residuos/DP", x = "Valores Estimados") +
    scale_y_continuous(limits = c(-3.5, 3.5), n.breaks = 12) +
    scale_x_continuous(
      labels = scales::number_format(big.mark = ".", accuracy = 1)
    ) +
    scale_fill_manual(values = c("blue", "red")) +
    theme_bw()
```


```{r}
  ## Graficos de elasticidade da função no ponto médio
  lista_elasticidade <- elasticity_plots(
    modelo = modelo_reg,
    df = df_dados,
    trans = transformacoes,
    vari_uti
  )

```